apiVersion: v1
kind: Secret
data:
  sugarizer.ini: {{(tpl (.Files.Get "sugarizer.ini") .) | b64enc}}
metadata:
  name: sugarizer-env
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sugarizer-deployment-server-{{required "schoolShortName not defined" .Values.schoolShortName}}
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
      school: {{required "schoolShortName not defined" .Values.schoolShortName}}
  template:
    metadata:
      labels:
        app: http
        school: {{required "schoolShortName not defined" .Values.schoolShortName}}
    spec:
      containers:
      - name: sugarizer-http
        image: mikkl/sugarizer-server
        volumeMounts:
        - name: env
          mountPath: "/opt/sugarizer-server/env"
          readOnly: true
      volumes:
      - name: env
        secret:
          secretName: sugarizer-env

---